

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    networks:
      - webash_net

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   restart: always
  #   ports:
  #     - ${REDIS_PORT}:6379
  #   volumes:
  #     - redis_data:/var/lib/redis/data

volumes:
  postgres_data:
  # redis_data:

networks:
  webash_net:
    driver: bridge
