"""create users table

Revision ID: 45436f294ff3
Revises:
Create Date: 2025-01-09 00:08:36.988795

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "45436f294ff3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("tid", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=200), nullable=True),
        sa.Column("last_name", sa.String(length=200), nullable=True),
        sa.Column("username", sa.String(length=200), nullable=True),
        sa.Column("is_bot", sa.Boolean(), nullable=False),
        sa.Column("language_code", sa.String(length=2), nullable=False),
        sa.Column("is_premium", sa.Boolean(), nullable=True),
        sa.Column("added_to_attachment_menu", sa.Boolean(), nullable=True),
        sa.Column("can_join_groups", sa.Boolean(), nullable=True),
        sa.Column("can_read_all_group_messages", sa.Boolean(), nullable=True),
        sa.Column("supports_inline_queries", sa.Boolean(), nullable=True),
        sa.Column("can_connect_to_business", sa.Boolean(), nullable=True),
        sa.Column("has_main_web_app", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_users_tid"), "users", ["tid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_tid"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
