"""Change phone_number column from str into int type

Revision ID: 71895d841d6e
Revises: 58f0a3b34b9a
Create Date: 2025-02-09 01:36:57.459270

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision: str = "71895d841d6e"
down_revision: Union[str, None] = "58f0a3b34b9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "phone_number",
        existing_type=sa.VARCHAR(length=20),
        type_=src.core.base.types.DigitsOnlyInteger(),
        existing_nullable=False,
        postgresql_using="phone_number::BIGINT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "phone_number",
        existing_type=src.core.base.types.DigitsOnlyInteger(),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
