name: Test

on:
  pull_request:
    branches:
      - dev

jobs:
  test_code:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_DB: ${{ secrets.TEST_DB_NAME }}

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependancy manager
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="/home/runner/.local/bin"
          poetry config virtualenvs.create false

      - name: Install dependencies with poetry
        run: poetry install --no-root

      - name: Run code tests
        run: pytest -s

      - name: Install ruff linter
        run: poetry add ruff

      - name: Run linters
        run: ruff check .
