name: Development

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
    branches:
      - dev

jobs:
  testing:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_DB: ${{ secrets.TEST_DB_NAME }}

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependancy manager
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="/home/runner/.local/bin"
          poetry config virtualenvs.create false

      - name: Install dependencies with poetry
        run: poetry install --no-root

      - name: Run code tests
        env:
          ACCESS_TOKEN_EXPIRE_SECONDS: ${{ secrets.ACCESS_TOKEN_EXPIRE_SECONDS }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DOCKER_SOCKET_PATH: ${{ secrets.DOCKER_SOCKET_PATH }}
          REFRESH_TOKEN_EXPIRE_SECONDS: ${{ secrets.REFRESH_TOKEN_EXPIRE_SECONDS }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
          TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
        run: pytest -s

      - name: Install ruff linter
        run: poetry add ruff

      - name: Run linters
        run: ruff check .


  automerge:
    needs: testing
    runs-on: ubuntu-latest
    permissions:
          pull-requests: write
          contents: write
    steps:
      - name: Get Pull Request Number
        run: echo "PR_NUMBER=$(gh pr view dev --json number -q .number || echo "")" >> $GITHUB_ENV

      - name: automerge
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
          PULL_REQUEST: "${{ env.PR_NUMBER }}"

  # main_pr:
  #   needs: [testing, automerge]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #       with:
  #         ref: dev
  #     - name: Create Pull Request
  #       uses: peter-evans/create-pull-request@v5
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         base: dev
  #         branch: main
  #         title: "Merge Dev into Main"
  #         body: |
  #           This pull request was automatically created by the GitHub Actions workflow.
